# Generated by Django 3.1.5 on 2021-01-11 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM_CONTACTO', models.CharField(max_length=50)),
                ('RUT_CONTACTO', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-]*$', 'Solo se permiten letras, números, guión y punto.')])),
                ('APELLP_CONTACTO', models.CharField(max_length=50)),
                ('APELLM_CONTACTO', models.CharField(max_length=50)),
                ('TELEFONO', models.IntegerField(default=0)),
                ('EMAIL', models.CharField(max_length=80)),
                ('DIRECCIÓN', models.CharField(max_length=100)),
                ('REGION', models.IntegerField(default=0)),
                ('PROVINCIA', models.IntegerField(default=0)),
                ('COMUNA', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_EMPRESA', models.CharField(max_length=30)),
                ('RUT_EMPRESA', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-]*$', 'Solo se permiten letras, números, guión y punto.')])),
                ('DIRECCIÓN', models.CharField(max_length=100)),
                ('REGION', models.IntegerField(default=0)),
                ('PROVINCIA', models.IntegerField(default=0)),
                ('COMUNA', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_EMPRESA', models.IntegerField(default=0)),
                ('ID_CONTACTO', models.IntegerField(default=0)),
            ],
        ),
    ]
